### ISSUE TITLE
The tests shouldn't use the user's local configuration

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#430] opened 2015-10-20 19:38 UTC
The tests currently source my bash profile, which makes them slower than they could be. In general, the tests should avoid using any user configuration to make them reproducible and to avoid false positive test failures.

**Comment by krader1961** [comment] 2015-11-08 21:03
I reported the following problem in issue #479 but since ~scopatz point out a closely related problem had already been reported in this issue I'll simply include my observations here and close #479.

While working on a change to make the history code lint clean I ran all the unit tests and was surprised to find that nosetests hung. Long story short: The problem is that commit e78564b interacts badly with my ~/.xonshrc file that contains a source command. If I revert that change or remove the source command from my ~/.xonshrc the replay unit test runs to completion. What is perplexing is why my ~/.xonshrc affects only that one test as there is nothing in it that would affect the behavior of the history susbsystem.

My first observation is that unit tests must be hermetic. They should never, ever, be affected by things like an individuals .xonshrc config file. At my day job this isn't an issue because unit tests never run on someones workstation (they always run "in the cloud" on a server with a borg standard config). Achieving a similar result in the context of a project like xonsh almost certainly will require a wrapper around nosetests that sets environment variables and/or run-time options to ensure that the local configs do not affect the test. For example, running the test via

```
XONSHRC=/dev/null nosetests -v tests/test_replay.py
```

runs to completion and passes. My recommendation is a Makefile that contains a "test" target that does what is needed so a developer can simply type "make test". Similarly for "make lint". It may also be possible and sensible for those parts of the code that sources local configs to test if it being executed via nosetests and skip loading the local config.

So people don't have to figure out how to display the relevant part of the change which caused the problem on my worstation it is this:

```
diff --git a/xonsh/shell.py b/xonsh/shell.py
index 152d336..71a4f3e 100644
--- a/xonsh/shell.py
+++ b/xonsh/shell.py
@@ -59,7 +59,7 @@ class Shell(object):
         if ctx is not None:
             self.ctx = ctx
         else:
-            rc = env.get('XONSHRC', None)
+            rc = env.get('XONSHRC')
             self.ctx = xonshrc_context(rcfile=rc, execer=self.execer)
         builtins.__xonsh_ctx__ = self.ctx
         self.ctx['__name__'] = '__main__'
```

**Comment by scopatz** [comment] 2015-11-09 04:15
Would you mind putting in a pr for this?

**Comment by scopatz** [comment] 2015-11-09 04:16
Thanks a ton!

**Comment by krader1961** [comment] 2015-11-12 07:38
@asmeurer can you test whether my pull request to add a Makefile, https://github.com/scopatz/xonsh/pull/492, fixes your issue? Or, equivalently, simply running the tests via `XONSHRC=/dev/null nosetest` stops the sourcing of your bash config?

**Comment by asmeurer** [comment] 2015-11-12 17:21
Setting that environment variable does indeed seem to make it not use my configuration (at least the tests run faster). IMHO the tests should always run this way, not just when run from a special script.

**Comment by krader1961** [comment] 2015-11-12 19:56
> IMHO the tests should always run this way, not just when run from a special script.

Agreed. I had hoped that nose would set an environment variable. However I couldn't find anything in the nose documentation to that effect. I also dumped the environment as a test was running and saw nothing useful. And since the script is still useful for easily running just the tests most likely to be affected by a change before it is committed it seems like a reasonable, straightforward, solution to the problem. Too, it wouldn't surprise me if we find it necessary to make other changes to the environment before running the tests.

**Closed** 2015-11-16 03:30 UTC
Labels: bug
