### ISSUE TITLE
FileNotFoundError while install xonsh via pip

### ISSUE THREAD

**Issue by admire93** [scopatz/xonsh#8] opened 2015-03-10 03:59 UTC
`$ pip install xonsh`  throw me a error.

```    
  Remove xonsh/lexer_table.py
    
    Remove xonsh/parser_table.py
    
    Building lexer and parser tables.
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/5h/8ys4czvj0qx270tbhljfpvg40000gn/T/pip-build-tseve78h/xonsh/setup.py", line 95, in <module>
    
        main()
    
      File "/private/var/folders/5h/8ys4czvj0qx270tbhljfpvg40000gn/T/pip-build-tseve78h/xonsh/setup.py", line 35, in main
    
        with open('readme.rst', 'r') as f:
    
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.rst'
    
    ----------------------------------------
```

**Comment by scopatz** [comment] 2015-03-10 04:13
I think that this is a duplicate of #1 and #3. The current master should work. Please let me know either way!

**Comment by admire93** [comment] 2015-03-10 04:16
thanks!

**Closed** 2015-03-10 04:15 UTC

**Comment by sanchopanca** [comment] 2015-03-11 06:10
I think, you should definitely update the pypi-package.

**Comment by scopatz** [comment] 2015-03-11 07:13
Updated.

**Comment by admire93** [comment] 2015-03-12 16:58
:+1:
