### ISSUE TITLE
$() expects only unicode output

### ISSUE THREAD

**Issue by ZyX-I** [scopatz/xonsh#447] opened 2015-10-30 13:59 UTC
Consider the following command:

    echo $(printf '\\x99')

. This will yield

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

The same thing happens when I try to use `$(ls -l)` in my home directory (I have a number of directories with “strange” names for testing my scripts).

$LANG is ru_RU.UTF-8.

Xonsh version 0.2.2.

**Comment by scopatz** [comment] 2015-10-30 15:31
Hmm these seems bad.  Where are you setting $LANG at? I have found that it needs to be set at the system level.  xonsh relies on Python's `sys.getdefaultenconding()` implicitly - or it should - in all cases. Setting lang at the system level seems to be the only way to do this. I have also found that I need to set `$LC_MESSAGES` equal to the same value as $LANG (and in the same place, `/etc/default/locale` for me.).

**Comment by ZyX-I** [comment] 2015-10-30 15:34
@scopatz I am running xonsh from zsh. $LANG is set in /etc/env.d/99locale (functionally) or /etc/profile.env (file generated from /etc/env.d and actually sourced by shells), but xonsh is supposed to inherit it from zsh.

**Comment by ZyX-I** [comment] 2015-10-30 15:38
@scopatz In any case xonsh should not limit itself to only valid UTF-8, regardless of locale: I have seen zip archives which produce weird sequences in file names after unpacking, and unzip with USE=natspec is not always fixing this.

In xonsh `locale` has some strange output:

```Shell
LANG=ru_RU.UTF-8
LC_CTYPE=ru_RU.UTF-8
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=C
LC_MESSAGES=C
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

. In zsh from where I launch xonsh it is

```Shell
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

: note no “C” sets.

**Comment by ZyX-I** [comment] 2015-10-30 15:40
@scopatz Running xonsh with `LC_ALL=ru_RU.UTF-8` in addition to inherited `$LANG` fixes `locale` output, but not the issue.

**Comment by ZyX-I** [comment] 2015-10-30 15:42
`env | grep LC` in xonsh:

 ```Shell
LC_NUMERIC=C
LC_MONETARY=C
LC_TIME=C
LC_ALL=ru_RU.UTF-8
READNULLCMD=/usr/bin/less
LC_MESSAGES=C
LC_COLLATE=C
LC_CTYPE=ru_RU.UTF-8
```

. Where is it getting `C` variables from? Zsh from where it is launched only has `READNULLCMD` from this list.

**Comment by scopatz** [comment] 2015-10-30 15:56
I think I see where the problem is.  Potential fix incoming.

**Comment by scopatz** [comment] 2015-10-30 16:04
Would you mind trying out #450?

**Comment by scopatz** [comment] 2015-10-31 20:35
Please close this issue @ZyX-I if you are happy with the current behaviour on master.

**Closed** 2015-10-31 20:41 UTC
Labels: bug
