### ISSUE TITLE
KeyError when exiting xonsh

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#202] opened 2015-04-09 21:53 UTC
```
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/shell.py", line 131, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/execer.py", line 124, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 551, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 527, in run_subproc
    wait_for_active_job()
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/jobs.py", line 92, in wait_for_active_job
    job = builtins.__xonsh_all_jobs__[act]
KeyError: 1
```

This was after typing `Ctrl-D` to exit xonsh.

**Comment by scopatz** [comment] 2015-04-10 04:04
Hmmm, any ideas @wrywerytwreywery?

**Comment by wrywerytwreywery** [comment] 2015-04-10 09:02
My first guess is that this is related to (and caused by) the issue from #201.

My first guess is that there could be a condition where a process finishes before we try to get its process group, which could cause the error in #201.  In that case, even though the job wasn't stored properly, we have already set `__xonsh_active_job__` to be this new process number.  So then, after #201 happens, running another command would cause xonsh to try to wait for that job (nonexistent) to finish.

I would guess, then, is that this isn't mac specific, but is a kind of race condition that I've just never happened to land on the wrong side of.  Can't say for sure, but I think the above would explain both this issue and #201.  I think I should have some time to fix this today, assuming that is actually what is happening.

**Comment by wrywerytwreywery** [comment] 2015-04-10 10:42
I was also able to replicate this another way:
```
$ cd ~ &
```

This shows that there is, in fact, a bug in the job control logic (and, specifically, with the way `ProcProxy` is handled.  I believe I have a fix in place on my local machine; I will test some more and then submit a PR.

**Comment by scopatz** [comment] 2015-04-13 06:20
@asmeurer can you confirm that the current master (0677827) solves this problem?

**Comment by scopatz** [comment] 2015-04-13 06:21
Thanks!

**Comment by scopatz** [comment] 2015-04-17 02:01
ping @asmeurer...

**Comment by asmeurer** [comment] 2015-04-17 05:11
I don't know how to reproduce it.

**Comment by rbrewer123** [comment] 2015-08-19 05:49
@scopatz and @asmeurer, I confirmed that @adqm's `cd ~ &` test above shows no problem in the current master on Ubuntu 14.04 and Windows 10.  I recommend closing this issue.  What do you think?

**Comment by scopatz** [comment] 2015-08-19 14:00
Yep, let's go ahead and close this.  Thanks for the reminder :)

**Closed by scopatz** 2015-08-19 14:00 UTC
Labels: bug
