### ISSUE TITLE
Double star (**.py) globbing

### ISSUE THREAD

**Issue by Carreau** [scopatz/xonsh#451] opened 2015-10-30 18:41 UTC
One of the feature that still makes me go back to fish is the double star wildcard/globing, that automatically expand to subdirectories.

[glob2](https://pypi.python.org/pypi/glob2) could I guess help for that.

**Comment by scopatz** [comment] 2015-10-30 18:45
Thanks for reporting @Carreau. I thought that this was in xonsh already, but I guess I am wrong.  Pull requests welcome :)  This shouldn't be too hard to implement. We already do some custom glob manipulation. I think it is in tools or `built_ins`

**Comment by Carreau** [comment] 2015-10-30 18:47
Well, sorry title is imprecise. `**/*.py` works but `**.py` does not, I typed too fast.

**Comment by Carreau** [comment] 2015-10-30 18:49
and the difference is that `**.py` will also match all py file in cwd :+1: 
see fish difference (`setup.py`):

```
$ ls -1 **/*.py | head
docs/conf.py
tests/test_aliases.py
tests/test_builtins.py
tests/test_dirstack.py
tests/test_environ.py
tests/test_execer.py
tests/test_foreign_shells.py
tests/test_history.py
tests/test_imphooks.py
tests/test_lazyjson.py
~/d/xonsh (master) $ ls -1 **.py | head
docs/conf.py
setup.py   <- this is globbed.
tests/test_aliases.py
tests/test_builtins.py
tests/test_dirstack.py
tests/test_environ.py
tests/test_execer.py
tests/test_foreign_shells.py
tests/test_history.py
tests/test_imphooks.py
```

I know it's a detail, and not really a "bug', but that annoy me :-)

**Comment by asmeurer** [comment] 2015-10-30 19:00
I'd also like to see support for bash's extended globbing (http://www.linuxjournal.com/content/bash-extended-globbing). The negated wildcards are particularly useful. It doesn't look like glob2 supports that. Maybe there is some other library. Or maybe xonsh should just implement its own globbing.

**Comment by scopatz** [comment] 2015-10-30 19:06
> Or maybe xonsh should just implement its own globbing.

I am most in favor of this, to keep the number of dependencies down.

**Comment by scopatz** [comment] 2015-10-30 19:06
Very willing to borrow other people's code, though, given the right license.

**Comment by krader1961** [comment] 2015-11-14 03:43
@Carreau The problem is that different shells have different behavior for such matters. In zsh `**.py` only matches files in the cwd. Yet `**/*.py` matches files in the cwd and subdirectories. I haven't used fish but the zsh behavior seems more reasonable than the fish behavior (assuming I've understood your point).  Also, your example is ambiguous. You apparently not only changed the shell but also the pattern. Which makes the results incomparable.

Since I'm moving from zsh my vote is that xonsh support zsh style globbing where `**/*.py` includes matching files in the cwd. But I'm perfectly happy if xonsh implements fish style globbing where `**.py` recurses into subdirectories. We should implement one or the other.

Regarding @asmeurer's proposal to implement full support for bash style globbing (or zsh or fish globbing) I'm ambivalent. Given the nature of xonsh, in particular the @() syntax the question is how much support should there be for non-python syntax. In theory bash, fish and zsh style globbing can all be accommodated via appropriate python functions invoked via @(). On the other hand for interactive use we want to minimize seemingly needless characters for common situations. How much syntactic "sugar" do we want to add? How much risk does that pose for creating ambiguous input or the ability to cleanly extend the syntax in the future?

**Comment by krader1961** [comment] 2015-11-14 03:58
@scopatz I recommend removing the "bug" label. This seems to be purely a feature request. And one that is going to require some discussion before any changes are merged.

**Comment by scopatz** [comment] 2015-11-14 17:48
Removed the bug label.  Also, note that the `**` syntax is supported currently by the lexer and parser. However, it just does normal single `*` globbing which isn't exactly expected... even by me!

**Comment by denfromufa** [comment] 2016-01-11 22:32
+1 on nested wildcard/regex completion for files and directories

**Comment by scopatz** [comment] 2016-01-11 22:38
All this takes is someone to implement it :)

**Comment by scopatz** [comment] 2016-01-11 22:40
The hooks to the parser are already there, just the  `__xonsh_glob__()` ie `xonsh.built_ins.globpath()`  function needs to be modified.

**Comment by scopatz** [comment] 2016-05-08 21:57
This has now been implemented by @Carreau. Please reopen if not up to expectations.

**Closed by scopatz** 2016-05-08 21:57 UTC
Labels: feature, help wanted
