### ISSUE TITLE
Ambiguity between subproc and python mode

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#913] opened 2016-05-16 20:54 UTC
Hello,

It seems there might a problem in the parser, I can't do this: 

`echo @("foo") > bar` 

Without having a parse error.On the other side this is accepted: 

`$(echo @("foo") > bar)`

Is it a bug ? 

__Error__:

```
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: @(',)
```

**Comment by scopatz** [comment] 2016-05-16 22:18
Interestingly, with the new matrix multiply, this is an ambiguous case between pure python and subproc mode, like with `ls -l`.  That is why it works when you explicitly put it in subproc mode.  Not sure why this is a parser error, though.  It should be a name lookup error for failing to find `echo`.  I can reproduce this, and marking this as a bug.

**Comment by GuillaumeLeclerc** [comment] 2016-05-17 07:01
It's indeed a lookup error not a parsing one. But I think there is nothing perfect we could do if it's a ambiguity. Maybe we could consider:

- If there is a syntax error try to fall back to subproc mode
- Having a priority for subproc or python to decide when there is an ambiguity (and switch from one to the other using a shortcut)

Having to use subproc mode is not very convenient because new lines are displayed as `\n`

**Comment by melund** [comment] 2016-05-17 10:52
> Having to use subproc mode is not very convenient because new lines are displayed as \n

It shouldn't if you use the uncaptured subproc `$[ ]`

**Comment by scopatz** [comment] 2016-05-18 01:49
@GuillaumeLeclerc, can you post the full error please?

**Comment by ned2** [comment] 2016-05-19 01:14
I just came across this today after updating xonsh to the contents of the master branch, finding a previously working script to have now broken. For that command `echo @("foo") > bar` I see this output:

````
    debug_level=self.debug_level)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 288, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 2301, in p_error
    column=p.lexpos))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 383, in _parse_error
    raise err
SyntaxError: eod.xsh:1:14: "]" at (1, 14) ends "@(" at (1, 7) (expected ")")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 234, in main
    run_script_with_cache(args.file, shell.execer, glb=shell.ctx, loc=None, mode='exec')
  File "/usr/local/lib/python3.5/dist-packages/xonsh/codecache.py", line 135, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/codecache.py", line 96, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/execer.py", line 95, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/execer.py", line 70, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/execer.py", line 209, in _parse_ctx_free
    raise original_error
  File "/usr/local/lib/python3.5/dist-packages/xonsh/execer.py", line 152, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 288, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 2305, in p_error
    column=p.lexpos))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 383, in _parse_error
    raise err
SyntaxError: eod.xsh:1:5: ('code: @(',)
````

**Comment by scopatz** [comment] 2016-05-19 01:17
@ned2, out of curiosity, did the previously working code used to work on Python 3.4 but now doesn't work on Python 3.5?

**Comment by ned2** [comment] 2016-05-19 01:41
I'm 95% sure I was running Python 3.5 when it was working. Small amount of uncertainty due to the fact that I've been playing around with pyenv recently, so some other version may have run it. But it seems like xonsh is just using the default system Python rather than any of my local pyenv version anyway, so it doesn't look like that's likely scenario.

Actually xonsh doesn't seem to be installed into the system Python 3.4, so no, was definitely running Python 3.5

**Comment by scopatz** [comment] 2016-05-19 02:39
Thanks for double checking @ned2

**Comment by scopatz** [comment] 2016-05-19 22:29
OK, I have figured this one out.  Fix incoming.

**Comment by scopatz** [comment] 2016-05-19 22:54
See #948

**Comment by ned2** [comment] 2016-05-20 01:10
Nice!

**Comment by scopatz** [comment] 2016-05-20 01:49
Feel free to close this @GuillaumeLeclerc!

**Comment by gforsyth** [comment] 2016-05-26 13:29
Closing this -- please reopen if the issue persists.

**Closed by gforsyth** 2016-05-26 13:29 UTC
Labels: bug
