### ISSUE TITLE
reverse search not interrupted by ^C

### ISSUE THREAD

**Issue by eldamir** [scopatz/xonsh#78] opened 2015-03-17 08:27 UTC
When i press ctrl+r to search my command history, I sometimes want to cancel that search. In Bash, I do so by hitting ctrl+c (^C).

In xonsh, the ctrl+c stroke returns my to a fresh prompt, but as I type, it continues the search from before:

```
ruben@krogan:~ 
(failed reverse-i-search)`entr': cd workspace/contract_management/
ruben@krogan:~ 
(failed reverse-i-search)`entrs': 

```

**Comment by scopatz** [comment] 2015-03-18 05:44
Thanks for reporting @eldamir.  I am not able to reproduce this. Crtl-c seems to do the right thing in Crtl-r mode.

**Comment by scopatz** [comment] 2015-03-18 05:45
What kind of system are you on? Where did you get Python from, etc?  What does the following do?

```python
$ python -c 'import readline'
```

**Comment by wrywerytwreywery** [comment] 2015-03-18 10:50
I have this problem as well.  As @eldamir described, if I hit ctrl-c in ctrl-r mode, it shows a fresh prompt, but typing at that prompt continues the search from earlier.  Hitting Return breaks out of the incremental search, but also runs the command it found, so that's not ideal. 

Ubuntu 14.04
Python 3.4.0 from APT

**Comment by scopatz** [comment] 2015-03-19 00:28
I have posted a suggested solution in #91

**Comment by wrywerytwreywery** [comment] 2015-03-29 19:27
I tried out the suggestion in #91 (calling `reset_line_state` on receiving a `KeyboardInterrupt`), but it did not work for me.  I also tried a few other functions within libreadline that looked promising (`free_line_state`, for one), but nothing seemed to do the trick.  I also tried updating Python to 3.4.3 from Python 3.4.0, but that didn't fix, either.

Looking at the docs, it seems like readline should already be trying to call those functions when catching `SIGINT` (and it should be handling `SIGWINCH` to do the terminal resizing, which was an issue for me earlier), so these hooks shouldn't be necessary.  That said, after a little bit of digging, it looks like readline changed the way it handles signals in 6.3 (see [here](https://bugs.python.org/issue23735)).  But I have the same issue on a Debian machine with libreadline 6.2, so that seems unlikely as an explanation.

@scopatz, since you haven't seen any of these issues, can you post what version of libreadline and Python you're using?  

I will also try to set up a VM with more up-to-date software for testing.

**Comment by wrywerytwreywery** [comment] 2015-03-29 20:32
FWIW, though, Python's REPL also has this bug (or maybe it's somehow intentional?), so I don't think there is going to be an easy fix.

**Comment by scopatz** [comment] 2015-03-29 20:37
Here is my system:

```console
scopatz@athenaie ~ $ python -V
Python 3.4.3 :: Continuum Analytics, Inc.
scopatz@athenaie ~ $ from xonsh import shell
scopatz@athenaie ~ $ import ctypes
scopatz@athenaie ~ $ rlver = ctypes.c_int.in_dll(shell.RL_LIB, 'rl_readline_version').value
scopatz@athenaie ~ $ rlver//256, rlver%256
(6, 2)
```

And for bugs that Python's REPL shares, the fix pretty much has to go through ctypes.

**Comment by wrywerytwreywery** [comment] 2015-03-31 02:10
Also, a few (seemingly unresolved) bug reports filed in IPython as well for this same issue, so we're not alone.

Apparently the default readline binding to abort the search is ctrl-g, not ctrl-c; so using that is a workaround (that, it seems, or hitting ctrl-c twice).  

I can try to take a look in the next day or so, to try to figure out how bash handles this (since ctrl-c seems to work to cancel the search in bash) and to mimic that behavior.

**Comment by rbrewer123** [comment] 2015-05-12 06:39
I'm seeing this bug on Windows too with Python 3.4.3 and pyreadline 2.0.  Neither ctrl-c (multiple times) nor ctrl-g (multiple times) stop the reverse search.  ctrl-g seems to restart the previous reverse search.  ctrl-c followed by return exits the reverse search.

**Comment by scopatz** [comment] 2015-05-12 15:39
My hope is that @anula's work on prompt-toolkit can fix this in some circumstances.

**Comment by anula** [comment] 2015-05-12 16:14
With prompt_toolkit it seems to work without problems on Ubuntu 14.04, on Windows I have it yet to check, but I guess it would require more people to confirm if it really works.

**Comment by eldamir** [comment] 2015-06-02 06:02
Sorry, I havn't been partaking in the discussion. I have had little time to look into the issue. The workaround from @rbrewer123 about using ctrl+g instead of ctrl+c seems to work for me.

**Comment by scopatz** [comment] 2015-06-02 11:36
Ok! Thanks @eldamir. Please close this issue if you are satisfied :)

**Comment by eldamir** [comment] 2015-06-03 18:24
Well, it is sufficient for me to use the software, but it would be nice if it was possible to make it work with ctrl+c, since that is what most people are used to.
Would that be possible?

**Comment by scopatz** [comment] 2015-06-04 11:14
Does it work as expected with prompt toolkit?

**Comment by scopatz** [comment] 2015-06-04 11:15
I'd like to see this work with Crtl-c, as well, and if prompt-toolkit solves the problem, the great :)

**Comment by Baughn** [comment] 2016-05-16 13:47
This bug is still here. Pressing ctrl-c still does not work to abort searches; can you reopen?

**Comment by gforsyth** [comment] 2016-05-16 14:10
Confirmed that Ctrl-c does not cancel the search in the `readline` shell.  
Works fine in `prompt_toolkit`

**Comment by adqm** [comment] 2016-05-16 14:33
This had originally been marked as "wontfix" (at least in my head) because it appeared to be a problem with GNU Readline, and it affects other projects as well (it's not specific to xonsh), and the known/documented solution was to use `ctrl-g` to cancel the search.

That said, I think this is actually being resolved upstream (i.e., in Python proper).  Probably in the next releases, this will work by default (see [this Python issue](http://bugs.python.org/issue24266)), and there is a workaround for now (see [this demo](http://bugs.python.org/file39467/raw_input__workaround_demo.py)).  If no one else has dived in, then I will add in this workaround when I have time (this weekend?).

**Comment by adqm** [comment] 2016-05-18 04:43
I think #920 should resolve this, if anyone wants to give it a try!  Please let me know if there are any issues.

**Comment by scopatz** [comment] 2016-05-18 06:17
Feel free to close this @adqm, since you reopened it :)

**Closed** 2016-05-18 11:01 UTC
Labels: bug
