### ISSUE TITLE
Jupyter output is directed to console, not browser

### ISSUE THREAD

**Issue by esafak** [scopatz/xonsh#629] opened 2016-01-15 20:19 UTC
It is counter-intuitive and atypical of Jupyter kernels for the output of a command to be sent only to the console, as it currently seems to. If this is due to misconfiguration, please change the defaults so that this does not occur, and amend the documentation to explain how to change this behavior.
 
This applies to the [latest git commit](https://github.com/scopatz/xonsh/commit/b26568ede680f9869e2de53800478ddb295e87c6) installed with pip3 on Ubuntu 14.04.3.

**Comment by scopatz** [comment] 2016-01-15 20:20
Thanks for reporting @esafak. This definitely needs fixing.

**Comment by blink1073** [comment] 2016-01-17 13:57
I has just about to report this, as I am trying to update the metakernel version to use your recent changes.  I'll see if I can figure anything out.

**Comment by blink1073** [comment] 2016-01-17 14:00
We're using `sys.stdout.write` in metakernel and that works, it appears you are doing the same here: https://github.com/scopatz/xonsh/blob/master/xonsh/tools.py#L311

**Comment by blink1073** [comment] 2016-01-17 14:15
One problem is that only the second context manager was called, it should be:

```python
with redirect_stdout(out):
    with redirect_stderr(err):
        shell.default(code)
```

The other problem seems to be that the stdout is not affecting the context of `shell.default`, still digging.

**Comment by blink1073** [comment] 2016-01-17 14:38
I tinkered with the options passed to `compile` and `exec`, but I couldn't figure out a way to capture the `stdout`....

**Comment by scopatz** [comment] 2016-01-18 21:55
Hi @blink1073, we do a lot of redirection, which is probably what is confusing everything.  Out of curiosity, do you have `$XONSH_STORE_STDOUT = True` in your xonshrc. I wonder if that is causing additional issues.

**Comment by scopatz** [comment] 2016-01-19 03:59
For what it is worth @blink1073, you can check out #634 for what I had to do to get redirect working. Redirecting the uncaptured subprocesses is the trickiest. I ended up implementing new builtin variables that you can attach a file-like object to.

**Comment by blink1073** [comment] 2016-01-19 17:08
I can confirm #634 fixes the issue.  I tried it with and without `$XONSH_STORE_STDOUT = True` before  using #634 and it had no effect.

**Comment by blink1073** [comment] 2016-01-19 17:09
I should be able to get this working on Windows.  If so, do you want to just include the Xonsh Metakernel as a dependency?

**Comment by blink1073** [comment] 2016-01-19 17:12
I can give you commit rights to the repo.

**Comment by scopatz** [comment] 2016-01-19 19:49
> If so, do you want to just include the Xonsh Metakernel as a dependency?

As a dependency for xonsh itself?

**Comment by blink1073** [comment] 2016-01-19 19:54
Either that or not include it in `xonsh`.  I'd prefer to only have one.  If you want to keep yours, I'd deprecate mine.

**Comment by scopatz** [comment] 2016-01-19 20:58
Personally, I'd rather not add more optional dependencies to xonsh itself and I am happy to have the version in their as it stands now.  I thought that the metakernel version did something slightly different, though, by spinning up a separate shell process and communicating via stdin / stdout / stderr.  The one in xonsh itself has exec's code more directly.  Am I mistaken about that and are these two truly redundant? I have glanced at your code but I don't really know how metakernel works....

**Comment by blink1073** [comment] 2016-01-19 21:00
I was spinning up a subprocess because I ran into problems when trying to use it directly that you have subsequently solved.  I am about to roll in the changes you have made.  They will be functionally equivalent, with the addition of the magics that metakernel supports out of the box.

**Comment by blink1073** [comment] 2016-01-19 21:04
There is also the problem of `pip` forcibly converting tar files to wheels, which will prevent your kernel from being installed by pip.

**Comment by scopatz** [comment] 2016-01-19 21:10
Uggh really. I hate pip.  I am pretty sure that conda handles this just fine.  

So I guess my take on this is that - even with the direct usage - the kernels actually have slightly different use cases.  The one in xonsh is for if you just want something that works (but may not install) and yours has the added metakernel fanciness (installs, but may has an additional dependency).

We should probably document this distinction somewhere :)

**Comment by blink1073** [comment] 2016-01-19 21:16
The problem is, the user ends up with two kernels.  I could call mine something different, but it is just too much confusion.

**Comment by blink1073** [comment] 2016-01-19 21:17
Unless we remain in concert and mine overrides yours, I suppose that isn't *too* bad.

**Comment by scopatz** [comment] 2016-01-19 21:18
Maybe "Calypso Xonsh"?  Or they can override... Either way :)

**Comment by blink1073** [comment] 2016-01-19 21:23
okay, fair enough.

**Comment by scopatz** [comment] 2016-01-21 21:10
This has been fixed by #634. Please reopen if you feel otherwise.

**Closed by scopatz** 2016-01-21 21:10 UTC
Labels: bug
