### ISSUE TITLE
windows: ctrl-c inside git bash window exits xonsh

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#235] opened 2015-05-16 01:54 UTC
I'm not sure if this is a problem with msysGit bash, xonsh, or a strange interaction.  I'm observing this behavior with msysGit 1.9.5.20150319 on Windows 8.1 with xonsh using the just-merged Windows support.

Open File Explorer and navigate to a directory.  Right click, and choose 'Git Bash Here'.  Inside the git bash window, run xonsh.  At the xonsh prompt, press ctrl-c.  xonsh exits and you are left at the git bash prompt.

Running xonsh from a plain cmd.exe window or from a ConEmu window (a fancy terminal emulator) does not exhibit this behavior.  Therefore the workaround is to not run xonsh from within a git bash window.

**Comment by scopatz** [comment] 2015-05-17 20:39
That sounds weird.  Can anyone else reproduce this...

**Comment by wrywerytwreywery** [comment] 2015-05-17 20:54
I get the same behavior.  Maybe Git Bash is intercepting the ^C and interpreting that as "kill the child?"

Still works fine for me in `cmd.exe`, though.

**Comment by scopatz** [comment] 2015-05-17 20:55
Ahh ok.  Still this is weird, especially if ^C works in msys.

**Comment by gforsyth** [comment] 2016-04-15 19:16
This seems to be just a Git Bash problem.  According to [SO](http://stackoverflow.com/questions/23678045/control-c-kills-ipython-in-git-bash-on-windows-7) it also does the same to IPython and Python.

**Comment by scopatz** [comment] 2016-05-07 18:35
@gforsyth great to know.  This doesn't seem like a bug with xonsh then.  Perhaps this is something that we should label as won't fix and close, then? Any objections?

**Comment by gforsyth** [comment] 2016-06-05 19:06
Closing as per discussion.  This is a Git Bash issue.

**Closed by gforsyth** 2016-06-05 19:06 UTC
Labels: bug, wontfix
