### ISSUE TITLE
Can't pipe to grep

### ISSUE THREAD

**Issue by blarghmatey** [scopatz/xonsh#409] opened 2015-10-08 15:02 UTC
When I try to pipe the output of a command into grep I get no output even when there should be some. A simple example is when I run `ps aux | grep emacs` while there is an emacs process running. Performing the same operation in bash or zsh yields the expected process information.

I am using Xonsh on CPython 3.5 in Manjaro Linux on a 64 bit Linux 3.19 kernel.

**Comment by scopatz** [comment] 2015-10-10 02:14
Thanks for reporting @blarghmatey! I can reproduce this.  Sorry about the delay in repsonding, I have been setting up a new machine :).  I'll try to get to this this weekend.

**Comment by kseistrup** [comment] 2015-10-11 07:12
It works here:

```sh
~ $ ps aux | grep unbound
unbound  15639  0.0  0.3 116008 29612 ?        Ssl  Oct07   2:52 /usr/bin/unbound -d
~ $
```

Cython 3.5.0
xonsh 0.2.0.r32.g652f333
Linux 4.2.2 (x86_64) ArchLinux

**Comment by scopatz** [comment] 2015-10-11 15:19
@blarghmatey and @kseistrup - do you have `$XONSH_STORE_STDOUT` set to `True`? This seems to be causing the problem on my machine. Probably time to dive back into that TeePTY code...

**Comment by kseistrup** [comment] 2015-10-11 15:23
Setting `$XONSH_STORE_STDOUT=1` provokes the bug.  Removing the assigment, or setting `$XONSH_STORE_STDOUT=0` makes the expression behave as expected,

**Comment by blarghmatey** [comment] 2015-10-11 16:02
@scopatz That was the issue. Removing that from my `.xonshrc` made pipes work properly again.

**Comment by scopatz** [comment] 2015-10-11 16:02
Yeah, piping *should* work here too,  but that is a temporary fix.

**Comment by scopatz** [comment] 2015-10-11 16:45
Ok - hilariously, the problem is that grep is too fast to start up.

**Comment by scopatz** [comment] 2015-10-12 04:26
OK @blarghmatey and @kseistrup - I have merged in the PR so I can release it.  Please close this issue if the PR fixes things for you. Thanks!

**Comment by blarghmatey** [comment] 2015-10-12 10:44
So the TEEPTY_PIPE_DELAY setting allows me to pipe into grep while storing stdout in the history file. Interestingly, I'm now getting a `KeyError` for `FORMATTER_DICT` and `BASH_COMPLETIONS` with the latest release. Printing `__xonsh_env__` shows that neither of those keys are present in the environment.

**Comment by scopatz** [comment] 2015-10-12 15:33
OK - v0.2.2 should fix this.

**Closed** 2015-10-17 15:55 UTC
Labels: bug
