### ISSUE TITLE
--shell-type readline doesn't work

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#1072] opened 2016-06-03 03:20 UTC
If I start xonsh with `--shell-type readline`, it still uses prompt_toolkit. I have to uninstall prompt_toolkit to make it use readline.

**Comment by adqm** [comment] 2016-06-03 12:01
Confirmed.  It looks like the value that comes in from the command line arguments is being overridden by the value in the `.xonshrc`.

**Comment by adqm** [comment] 2016-06-03 12:15
This might make a good first patch for someone.  The issue is with [line 47 of `xonsh/shell.py`](https://github.com/scopatz/xonsh/blob/master/xonsh/shell.py#L47), which totally ignores the value of `shell_type` that was passed in (from the command line arguments).

What we should really do is first check the `shell_type` that was passed in, and only check the value from the environment if that is `None`

**Comment by adqm** [comment] 2016-06-05 03:06
Fixed in #1100; thanks @VHarisop!  @asmeurer, feel free to re-open if this doesn't work for you.

**Closed by adqm** 2016-06-05 03:06 UTC
Labels: bug, newcomer
