### ISSUE TITLE
Problem parsing a command ending with comment, like: $ ls # foo

### ISSUE THREAD

**Issue by naufraghi** [scopatz/xonsh#23] opened 2015-03-12 23:31 UTC
```
$ ls # foo
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/xonsh/shell.py", line 92, in default
    self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 108, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'ls' is not defined
```
Besides that, a very usable shell!

**Comment by scopatz** [comment] 2015-03-13 01:39
Thanks for reporting @naufraghi - I think I know what the problem is.

Thanks!

**Comment by scopatz** [comment] 2015-03-13 01:40
The problem has to do with the `subproc_line()` function being applied as `$[ls # foo]` instead of `$[ls] # foo`, for the interested.

**Comment by scopatz** [comment] 2015-03-14 06:41
I believe that I have a fix for this on my `sl` branch @naufraghi. Would you please try it out?

**Comment by scopatz** [comment] 2015-03-15 04:40
This should now be fixed on master

**Closed by scopatz** 2015-03-15 04:40 UTC
Labels: bug

**Comment by naufraghi** [comment] 2015-03-16 09:37
Sorry to be late, fix confirmed!

**Comment by naufraghi** [comment] 2015-03-16 09:37
Some pointer to add a regression test if not already done?

**Comment by scopatz** [comment] 2015-03-16 23:05
I did add some tests associated with this.
