### ISSUE TITLE
Virtualenv in xonsh shell

### ISSUE THREAD

**Issue by eldamir** [scopatz/xonsh#379] opened 2015-08-31 06:56 UTC
I have some weird behaviour sometimes, when running a command within a virtualenv in a xonsh shell, e.g.

```
 $ ~/venvs/v3env/bin/py.test --nomigrations .
Traceback (most recent call last):
  File "/Users/ruben/venvs/v3env/bin/py.test", line 7, in <module>
    from pytest import main
ImportError: No module named 'pytest'
```

Same command in bash

```
 $ ~/venvs/v3env/bin/py.test --nomigrations .
======================================= test session starts ========================================
platform darwin -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.2
rootdir: <redacted>, inifile: pytest.ini
plugins: cover, django, mock, splinter, xdist
collected 334 items
[...]
```

I can't imagine why this should be a problem. Seems like Xonsh tries to run it within its own Python environment instead of in *bash process mode*. Or, maybe the shebang line is not handled properly? The **py.test** script looks like this:

```
#!/Users/ruben/venvs/v3env/bin/python3.4

# -*- coding: utf-8 -*-
import re
import sys

from pytest import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by scopatz** [comment] 2015-08-31 13:49
@eldamir - I think I going to need more information to help you.

How did you activate the virtual env in xonsh? Did you use `source` or `source-bash`?

What are the values of `$PATH` and `$PYTHONPATH` in both xonsh and bash?

Can you create a minimally failing way to reproduce this that doesn't rely on a test suite?

**Comment by eldamir** [comment] 2015-08-31 15:09
```
mkdir xonsh379
cd xonsh379
virtualenv -p /usr/local/bin/python3
echo "#!env/bin/python3\nimport sys\nprint(sys.path)" > script.py
```

That's the minimal setup. Now we call with bash and xonsh.

**bash**
```
 $ env/bin/python script.py 
['/Users/ruben/Dropbox/workspace/random/xonsh379', 
'/Users/ruben/Dropbox/workspace/random/xonsh379/env/lib/python34.zip', 
'/Users/ruben/Dropbox/workspace/random/xonsh379/env/lib/python3.4', 
'/Users/ruben/Dropbox/workspace/random/xonsh379/env/lib/python3.4/plat-darwin', 
'/Users/ruben/Dropbox/workspace/random/xonsh379/env/lib/python3.4/lib-dynload', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', 
'/Users/ruben/Dropbox/workspace/random/xonsh379/env/lib/python3.4/site-packages']
```

**Xonsh**
```
 $ env/bin/python script.py 
['/Users/ruben/Dropbox/workspace/random/xonsh379', '/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python34.zip', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload', 
'/usr/local/lib/python3.4/site-packages']
```

These are both without activating the virtualenv, but simply running the python interpreter in the virtualenv directory, which works fine for bash.

Activating the virtualenv with `source-bash env/bin/activate` yields the same result

```
 $ source-bash env/bin/activate
 $ python script.py
['/Users/ruben/Dropbox/workspace/random/xonsh379', '/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python34.zip', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', 
'/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload', 
'/usr/local/lib/python3.4/site-packages']
 $ which python
/Users/ruben/Dropbox/workspace/random/xonsh379/env/bin/python  # Correct interpreter. Wrong paths
```

**Comment by eldamir** [comment] 2015-08-31 15:14
This is on Mac, mind you... I havn't had this issue on Ubuntu.

**Comment by scopatz** [comment] 2015-08-31 15:19
What happens when you `del sys.path[1]` from the xonsh cases? Does everything work then?

**Comment by scopatz** [comment] 2015-08-31 15:20
Oh, I guess the framework stuff is there too.

**Comment by scopatz** [comment] 2015-09-01 15:28
Hmmm I don't know enough about virtual env on macs to know what is going on here. Anyone have any ideas?

**Comment by eldamir** [comment] 2015-09-08 08:37
I can confirm that on Ubuntu, either running the minimal case above with `./script.py` or `env/bin/python script.py` produces identical and expected result.

**Comment by scopatz** [comment] 2015-09-11 01:57
Doubly strange!  Uggh.

**Comment by moigagoo** [comment] 2016-02-03 13:35
This issue is the only thing that stops me from using xonsh :-(

Sorry that I can't provide any helpful information, just confirming that the issue still exists.

**Comment by scopatz** [comment] 2016-02-03 15:32
Hi @moigagoo.  Sorry to hear that this is an issue for you.  Just out of curiosity, you are using xonsh on Mac OSX and plain-old-virtualenv (not virtualenvwrapper or xenv)?

**Comment by scopatz** [comment] 2016-02-03 15:34
Also what is your output of the `xonfig` command?

**Comment by moigagoo** [comment] 2016-02-03 15:38
I'm currently using pew as a virtualenv manager, but I tried to create a regular virtualenv with `python -m venv foo` and `source-bash`ing into it, and the result is the same. Which is really no wonder since pew creates regular virtualenvs.

**Comment by moigagoo** [comment] 2016-02-03 15:40
```
$ xonfig

+------------------+-------+
| xonsh            | 0.2.5 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | <0.57 |
| on posix         | True  |
| on linux         | False |
| on arch          | False |
| on windows       | False |
| on mac           | True  |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by scopatz** [comment] 2016-02-03 15:50
Which version of Bash are you on? You can check with `bash --version`

**Comment by moigagoo** [comment] 2016-02-03 18:10
I don't have my MacBook at the moment. I'll check the version tomorrow.
I don't use bash btw, I use zsh, if that's important.

**Comment by scopatz** [comment] 2016-02-03 20:04
hmmm but when you `source-bash` for activating the venv, you are using bash. So what Bash do you have?

**Comment by moigagoo** [comment] 2016-02-03 20:12
This is a question I can't answer right now since I left my MacBook at the office. I'll make sure to respond as soon as possible tomorrow.

**Comment by scopatz** [comment] 2016-02-03 20:18
Thanks a ton @moigagoo, whenever you are able is fine by me!

**Comment by moigagoo** [comment] 2016-02-04 06:40
Here you go:
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by scopatz** [comment] 2016-02-04 16:11
OK, thanks. That is what I thought.

**Comment by moigagoo** [comment] 2016-02-04 16:16
Is it a bash issue?

**Comment by scopatz** [comment] 2016-02-04 16:25
It might be a bash / venv issue.  Virtual env itself does a really silly thing in that the activate script creates a bash function that is then bound to non-exported (bash process only) environment variables.  You can see [the source code here](https://hg.python.org/cpython/file/3.5/Lib/venv/scripts/posix/activate).  This is fine as long as you are in exactly the same bash session, butthe moment that bash process ends the deactivate script and its variables go away.  

Because of this, there is literally a different venv script for every shell and platform (ps://hg.python.org/cpython/file/3.5/Lib/venv/scripts/posix).  The vitrualenvwrapper utility does things in a more sane way.  Also some people have put together a virtualxonsh for exactly this reason.  

It seems like virtualxonsh should either go into xonsh or Python at this point. However, I am not sure how this would solve the problem with pew...

**Comment by scopatz** [comment] 2016-02-04 16:26
And note that since venv and `source-bash` works on bash v4.1+, this particular issue might be because of an old version of bash.

**Comment by moigagoo** [comment] 2016-02-04 16:30
Holt molly, this is insane :-) Thanks for the clarification!

I'll update bash and report back if it helped. If it doesn't, I'll just switch to virtualxonsh; xonsh is too cool to dump because of a minor inconvenience.

**Comment by scopatz** [comment] 2016-02-04 16:37
Haha thanks :).  And I totally agree; it is insane.

**Comment by moigagoo** [comment] 2016-02-05 07:14
Updated bash to 4.3, it didn't help, `from sys import path; path` still yields the global paths. Bummer.

> It seems like virtualxonsh should either go into xonsh or Python at this point.

Seems like the right thing to do.

However, [virtualxonsh](https://github.com/riccardomurri/virtualxonsh/blob/master/vix.xsh) doesn't work for me:
```
$ xonsh vix.xsh
xonsh: vix.xsh: No such file or directory.

$ ./vix.xsh
xonsh: subprocess mode: permission denied: ./vix.xsh
```
Am I doing it wrong?

**Comment by scopatz** [comment] 2016-02-05 16:49
Yeah, So I think that you need to source or import the vix.xsh file in your xonshrc file.  Then you will ahev access to commands like `vix ls` and `vix activate`

**Comment by moigagoo** [comment] 2016-02-05 21:17
@scopatz Thanks for the tip! Unfortunately, they both seem to not work. I'm having the same path value after `vix activate`.

**Comment by scopatz** [comment] 2016-02-05 21:25
I think that this is all the more reason to bring vix into xonsh....

**Comment by moigagoo** [comment] 2016-02-05 21:43
If xonsh shipped with a sane virtualenv management tool, that'd be awesome.

Virtualenv management is messy, and there're lots of tools to solve the problem, some of them really hacky, including the default one.

At the same time, `There should be one-- and preferably only one --obvious way to do it`. So it would be great if xonsh offered _the_ tool to manage virtualenvs, so users wouldn't have to worry about it. Like, if you choose xonsh, you get a kickass shell _and_ you automatically solve the virtualenv problem.

I think, `vox` would be a great name for such tool. It has the familiar "x" and "o" from "xonsh" and "v" from "venv," plus the package name is [vacant](https://pypi.python.org/pypi/vox). And it means "voice" in Latin, which doesn't symbolize anything but is kind of nice :-)

It shouldn't necessarily be built in xonsh. It can be an optional requirement, defined in `extra_require` in setup.py.

I think I'll give it a try. I don't quite get how venvs work now, so I'll need time to dig in.

**Comment by moigagoo** [comment] 2016-02-09 11:30
@scopatz Here's [vox](https://github.com/moigagoo/vox)—a virtual environment manager for xonsh.

My goal was to make it as thin as possible. To create environments, it just invokes `python3 -m venv`. To activate an environment, it just adds a record to $PATH. Dead simple but does the trick.

If you like it, I'd be happy to see it included in xonsh.

Note: For some reason, if I put `from vox import *` in _.xonshrc_, the shell crashes on start with ImportError. Running the same command in a running shell is OK. Am I doing it wrong?

**Comment by scopatz** [comment] 2016-02-09 17:47
> If you like it, I'd be happy to see it included in xonsh.

Awesome! This is great. I'd love to see it in xonsh proper. Please put in a pull request and we can go from there.

> Note: For some reason, if I put from vox import * in .xonshrc, the shell crashes on start with ImportError. Running the same command in a running shell is OK. Am I doing it wrong?

That should work. I'll try it out this evening, but if you want you can post the error here too.

**Comment by moigagoo** [comment] 2016-02-09 20:25
@scopatz AFAIU there's no way to ship xsh files with xonsh. At least, I haven't found any xsh scripts that are imported by default.

Because of that, I've written a pure Python version of Vox. All seems to work fine, but I'm having trouble setting environment variables. I tried setting the variables via __xonsh_env__, builtins.__xonsh_env__, and xonsh.environ.Env, but failed. Could you please point me in the right direction?

**Comment by scopatz** [comment] 2016-02-11 01:17
A pure python version is fine, probably preferred.  if you need to set environment variables are runtime, you should be able to do so via `builtins.__xonsh_env__['VARNAME'] = value`, like you would with a dict.  

I think if you put in a pull request, we can go from there.

**Comment by melund** [comment] 2016-02-11 07:28
This is a great feature could it include support conda environments as well :)

**Comment by moigagoo** [comment] 2016-02-11 08:09
@melund Thanks! I guess we could add the `--conda` flag to the `new` command to make it invoke conda instead of venv. Something like `vox new --conda bar`, `vox enter bar`.

I haven't done research on the topic yet, but if conda environments can be activated by modifying $PATH like regular ones can, I don't see any problem with that.

I suggest you post this feature request in the Vox repo, so it doesn't get lost. When (and if) Vox is merged into xonsh, the feature request will move here.

**Comment by moigagoo** [comment] 2016-02-11 08:51
@scopatz Unfortunately, I'm getting an [AttributeError when calling `builtin.__xonsh_env__`](https://github.com/moigagoo/xonsh/commit/90b5cbe8515e675d9c61a0a7898c7979dff0308e#diff-eacee5f9d6bde937e44acbbc4b58a55cR9).

**Comment by funkyfuture** [comment] 2016-05-13 09:13
> I'm currently using pew as a virtualenv manager, but I tried to create a regular virtualenv with python -m venv foo and source-bashing into it, and the result is the same. Which is really no wonder since pew creates regular virtualenvs.

maybe this is a helpful hint: i noticed that using `pew` on OS X disables all bash completions which may be caused by the fact that it launches its own subshell. but it's just an assumption.

@moigagoo where did the `vox`-repo go? a venv-manager included in `xonsh` would be great.

**Comment by moigagoo** [comment] 2016-05-13 09:19
@funkyfuture Vox was [merged into xonsh](https://github.com/scopatz/xonsh/pull/675) in February.

**Comment by funkyfuture** [comment] 2016-05-13 09:26
> Vox was merged into xonsh in February.

it would be great if it wasn't only mentioned in the API documentation.

**Comment by moigagoo** [comment] 2016-05-13 10:20
Here you go: https://github.com/scopatz/xonsh/pull/881

**Comment by gforsyth** [comment] 2016-06-05 19:12
Ok -- Vox is in xonsh and also has a docs page.  I'm closing this.

**Closed by gforsyth** 2016-06-05 19:12 UTC
Labels: bug
