### ISSUE TITLE
Static Config: Can't use zsh as foreign shell

### ISSUE THREAD

**Issue by moigagoo** [scopatz/xonsh#662] opened 2016-02-05 09:22 UTC
```
$ cat ~.config/xonsh/config.json
"foreign_shells": [
        {"shell": "/bin/zsh"}
    ]

$ xonsh
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.5', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 166, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 153, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.5/site-packages/xonsh/shell.py", line 61, in __init__
    self._init_environ(ctx, config, rc)
  File "/usr/local/lib/python3.5/site-packages/xonsh/shell.py", line 99, in _init_environ
    self.execer = Execer(config=config)
  File "/usr/local/lib/python3.5/site-packages/xonsh/execer.py", line 40, in __init__
    load_builtins(execer=self, config=config)
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 673, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config))
  File "/usr/local/lib/python3.5/site-packages/xonsh/environ.py", line 1099, in default_env
    issue_warning=False))
  File "/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 379, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 151, in foreign_shell_data
    funcs = parse_funcs(s, shell=shell, sourcer=sourcer)
  File "/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 212, in parse_funcs
    namefiles = json.loads(g1.strip())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by moigagoo** [comment] 2016-02-05 09:23
No issues with bash though.

**Comment by scopatz** [comment] 2016-02-05 16:14
Hi @moigagoo, I think that this is duplicate of #484. We don't yet have native support for xonsh in zsh.  This is largely because I don't have enough experience with zsh to be confident that it would "just work". If you are willing to help test, I'd happily take a stab at implementing support.

Basically, it is just adding zsh script templates that do the work specified in http://xonsh.org/xonshconfig.html#foreign-shells  In my opinion, the only really tricky part is figuring out how to get the names of zsh functions and the files that they live in.

**Comment by scopatz** [comment] 2016-02-05 16:15
Again, I'd love to see this feature added!

**Closed** 2016-02-07 20:15 UTC
Labels: bug, duplicate
