### ISSUE TITLE
In .xonshrc, classes don't seem to bind their methods

### ISSUE THREAD

**Issue by abadger** [scopatz/xonsh#133] opened 2015-03-23 02:43 UTC
Current xonsh checkout: f44013b31756ba5491f2a7e1dffb7ad64513b28e
python: 3.4.1
OS: fedora 21

Here's a minimal .xonshrc that defines a class and then attempts to use it:

``` python
class Test:
    def __init__(self):
        self.msg('hello world')
    def msg(self, m):
        print(m)

$PF=Test()
```

Instead of storing an instance of the class in $PF, it throws the following error:

``` 
Traceback (most recent call last):
  File "scripts/xonsh", line 3, in <module>
    main()
  File "/srv/git/wishlist/xonsh/xonsh/main.py", line 36, in main
    shell = Shell()
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 94, in __init__
    execer=self.execer)
  File "/srv/git/wishlist/xonsh/xonsh/environ.py", line 168, in xonshrc_context
    execer.exec(rc, glbs={}, locs=env)
  File "/srv/git/wishlist/xonsh/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "/home/badger/.xonshrc", line 9, in <module>
  File "/home/badger/.xonshrc", line 260, in __init__
AttributeError: 'Test' object has no attribute 'msg'
Exception ignored in: <bound method Shell.__del__ of <xonsh.shell.Shell object at 0x7fb350b844e0>>
Traceback (most recent call last):
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 102, in __del__
    teardown_readline()
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 65, in teardown_readline
    import readline
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1908, in _get_spec
TypeError: 'NoneType' object is not iterable
```

Not sure if we are supposed to be able to store python code inside of environment variables however the problem is deeper than that; modifying the xonsh source code to try to access the class via the context also leads to the same error.

**Comment by scopatz** [comment] 2015-03-23 06:08
I am pretty sure this is the same as #131

**Comment by wrywerytwreywery** [comment] 2015-03-23 11:57
#131 seems to be fixed by passing `env` in as globals instead of locals to `execer.exec` in `xonsh/environ.py`.

This issue, though, seems to be a problem with the way class definitions are being handled.  

What seems to be happening in this specific example is that `msg` is being defined as a function on its own, outside the class `Test`.  So it's not being interpreted as part of `Test`'s `suite` (since there is a dedent to get back to `def msg`?), though that makes me wonder why anything works (function definitions should also be screwed up by this, I would think).

I might be able to find some time to take a look today.

**Comment by wrywerytwreywery** [comment] 2015-03-23 12:02
This might also be the same problem that underlies #134?

**Comment by wrywerytwreywery** [comment] 2015-03-24 01:38
From what I can tell, this seems to be a problem with `p_suite`, and in particular with the details of how `INDENT` and `DEDENT` are handled.  Nested functions also seem not to work, as an example.

I have something of a plan for a new lexer, making use of the `tokenize` module.  I think that change, along with some slight changes to the parser to make it match Python's grammar more closely, should fix this.

**Comment by scopatz** [comment] 2015-03-24 02:48
Doesn't tokenize only work on Python source code?

**Comment by scopatz** [comment] 2015-03-24 02:53
Also we should be able to write some simple tests for this.

**Comment by wrywerytwreywery** [comment] 2015-03-24 02:58
> Doesn't tokenize only work on Python source code?

Sort of.  It will produce tokens for things like `$` and `?` though, so we should be able to make good use of it.  So my thought was:
* lex using `tokenize` (should get indents/dedents "right", and should otherwise produce something very close to what your code is making)
* pass through the token stream to convert it to PLY tokens, and to parse out things like `$(` that wouldn't otherwise be valid syntax
* feed the resulting tokens into the `Parser` class as it exists now, modulo some changes to make `suite` match the Python grammar

I am not sure it will be quite so easy as that, but I think in the long run, there are going to continue to be parsing issues, and so we're better off if we use tools built in to Python where possible.  I won't be able to do much tonight, but I'll have some time tomorrow to work on this.  I can certainly write some tests, as well.

**Comment by scopatz** [comment] 2015-03-24 04:30
This affects if-statements too:

```console
scopatz@athenaie ~ $ if False:
`·.,¸,.·*¯`·.,¸,.·*¯    if 1:
`·.,¸,.·*¯`·.,¸,.·*¯       print(1)
`·.,¸,.·*¯`·.,¸,.·*¯    if 2:
`·.,¸,.·*¯`·.,¸,.·*¯       print(2)
`·.,¸,.·*¯`·.,¸,.·*¯ 
2
```

**Comment by scopatz** [comment] 2015-03-24 04:54
OK, so I think that this is a known issue and there are a number of PLY-based solutions out there [1-3].  Before you run off and try to rewrite the lexer with tokenize @wrywerytwreywery , I'd like to try a PLY solution. I think that this was just something that I overlooked originally, and not critical flaw.  I also think that ultimately it will be better (faster) to keep everything in PLY.

1. http://stackoverflow.com/questions/19773993/parsing-python-with-ply-how-to-code-the-indent-and-dedent-part
2. http://stackoverflow.com/questions/28259366/ply-return-multiple-tokens
3. http://dalkescientific.com/writings/diary/lolpython.py

**Comment by scopatz** [comment] 2015-03-24 04:54
Not that I don't appreciate the thought :)

**Comment by wrywerytwreywery** [comment] 2015-03-24 13:12
My feeling is that the benefits still outweigh the drawbacks; it should be much easier to get everything right if we just hook into Python's tokenizer, and most of the methods you linked to (which I had looked at) implement at least one post-processing step anyway, so I think the speed difference is likely to be negligible.  Otherwise, aren't we likely to be having this conversation again when some other weird Pythonism isn't handled properly?

That said, I'm happy to try either way / both ways.

**Comment by wrywerytwreywery** [comment] 2015-03-25 01:22
Hi @scopatz,

I spent a little bit of time earlier today trying to get a PLY version working, but I wasn't able to.  

However, I think I do have something working with tokenize.  I haven't updated the tests, but I ran it through everything on the tutorial and some of the syntax issues we had had trouble with over the last few days (including the original one in this post), and as far as I can tell, everything seems to be working as expected.

I won't submit a PR until I have the tests working, but if you want to take a look, it is up on the master branch of wrywerytwreywery/xonsh.

**Comment by wrywerytwreywery** [comment] 2015-03-25 23:20
Hi @abadger,  I think this should be resolved now on the current master (588fa2b377ff91af44dd11c10749697797d223ab).  Can you please verify?

**Comment by abadger** [comment] 2015-03-26 01:49
Progress!  It's not perfect but I can get something working if I obey some rules in addition to what python normally allows.

So here's something that works:

``` python
import subprocess
from xonsh import environ

class MyPromptFormatter(environ.DefaultPromptFormatter):
    def get_tty(self):
        tty = subprocess.check_output('tty').decode().strip()
        segments = tty.split('/')
        return '/'.join(segments[-2:])
    def __init__(self):
        environ.DefaultPromptFormatter.__init__(self)
        self['tty'] = self.get_tty

$PROMPT='{{CYAN}}[{tty}@{{hostname}}{{NO_COLOR}} {{cwd}}{{RED}}{{curr_branch}}{{NO_COLOR}}{{CYAN}}]{{NO_COLOR}}$ '.  format(tty=MyPromptFormatter().get_tty())
```
(Not doing anything fancy with DefaultPromptFormatter yet so you could just inherit from object and get rid of the super call to test on unmodified xonsh).

Things that don't work though:
* If ```__init__()``` comes before ```get_tty()``` we get this:

```
Traceback (most recent call last):
  File "scripts/xonsh", line 3, in <module>
    main()
  File "/srv/git/wishlist/xonsh/xonsh/main.py", line 41, in main
    shell = Shell() if not args.norc else Shell(ctx={})
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 94, in __init__
    xonshrc_context(rcfile=env.get('XONSHRC', None), execer=self.execer)
  File "/srv/git/wishlist/xonsh/xonsh/environ.py", line 299, in xonshrc_context
    execer.exec(rc, glbs=env)
  File "/srv/git/wishlist/xonsh/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "/home/badger/.xonshrc", line 12, in <module>
    
  File "/home/badger/.xonshrc", line 261, in __init__
AttributeError: 'MyPromptFormatter' object has no attribute 'get_tty'
Exception ignored in: <bound method Shell.__del__ of <xonsh.shell.Shell object at 0x7f52a4f5c4e0>>
Traceback (most recent call last):
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 102, in __del__
    teardown_readline()
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 65, in teardown_readline
    import readline
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1908, in _get_spec
TypeError: 'NoneType' object is not iterable
```
I'm guessing that the code isn't waiting until the end of the class definition is found to compile t```__init__```and so it doesn't know that a ```get_tty``` method will be defined later in the class.

* Any blank lines in the class lead to an error as well but that might be a separate issue or not a bug: At a python interactive command prompt a blank line would signal the end of a block.  I don't know if xonsh is taking the same position WRT scripts or if it should behave more like python scripts where blank lines don't make any difference.

**Comment by wrywerytwreywery** [comment] 2015-03-26 02:08
Are you sure you merged with master?  I am unable to reproduce either the issue with blank lines, or with defining `get_tty` before `__init__`.

**Comment by abadger** [comment] 2015-03-26 02:19
Doh!  I know what I did.  (pulled from my fork instead of fetching from upstream).  Let me retry my test.

**Comment by abadger** [comment] 2015-03-26 02:41
okay, with a fresh checkout it looks like those bugs are gone as well :-)  Everything I've tested looks good.

**Comment by wrywerytwreywery** [comment] 2015-03-26 02:53
Great; thanks!

**Comment by wrywerytwreywery** [comment] 2015-03-29 20:22
I believe this is resolved, so I am going to close this issue.  Please feel free to re-open if you feel that this hasn't been addressed properly.

**Closed by wrywerytwreywery** 2015-03-29 20:22 UTC
Labels: bug
