### ISSUE TITLE
Process exit codes not being set correctly

### ISSUE THREAD

**Issue by nicfit** [scopatz/xonsh#509] opened 2015-11-18 05:09 UTC
I see that the 'rtn' value of history dicts and 'returncode' on job objects does not capture the actual process return code. For example,
```bash
$ ls foobazz
ls: cannot access foobazz: No such file or directory
$ echo $?
2
```
In xonsh the values are 0, and signal success.

I've got a fix for Unix (unless deeper bits need touched) on a branch here:
https://github.com/scopatz/xonsh/compare/master...nicfit:exitcodes

At the suggestion of @krader1961 I took it a bit further and capture signal and coredump details also.

I'm not sure what is needed out in  ON_WINDOWS version of wait_for_active_job(..), if anything.

I'm attaching a test program* I used to verify and investigate the differences between Popen wait/poll and os.wait.. there is some missing in matching going on, but using os.wait sematics is correct.

-travis

Test program renamed .txt, to let github me to attached, odd.
[popen_test.txt](https://github.com/scopatz/xonsh/files/37515/popen_test.txt)

**Comment by nicfit** [comment] 2015-11-18 05:13
The test program is a messing, and I can clean up for nose.

Also, I had a go over the weekend and getting the parser to recognize "echo $?", but not luck. Yacc magic is not yet known.

**Comment by scopatz** [comment] 2015-11-18 13:39
Thanks for reporting @nicfit. Do you have stdout storage turned off? Just curious. Also please PR any changes you want to make.

**Comment by scopatz** [comment] 2015-11-18 13:41
Also, please make the rtn code stuff one PR and the $? another. The only reason have $? is for compatability, as it is terrible syntax.

**Comment by nicfit** [comment] 2015-11-19 01:41
I'm running with $XONSH_STORE_STDOUT=False, but I've since turned it on and see more is needed.

**Comment by krader1961** [comment] 2015-11-19 03:00
I'm confused by your comment, @scopatz, about having $? for compatibility. That could be interpreted to mean that xonsh supports $? but it clearly does not. Or were you implying that you would accept a PR to implement that var as a shortcut for the exit status of the most recent command? For that matter, the docs don't explain how to check the exit status of the most recent external command. It appears the correct way is `builtins.__xonsh_history__.last_cmd_rtn` but that is unwieldy.

**Comment by krader1961** [comment] 2015-11-19 03:05
@nicfit This is an important fix and I wouldn't normally be hard-nosed about unit tests but I think they're going to be mandatory for a change of this nature. Having said that I think your existing commits are a good step in the right direction. I'm going to install them on my system to see if xonsh history will correctly tell me why the most recent external command exited.

P.S., I think any change that fixes a defect must have relevant unit tests to prevent regressions.

**Comment by krader1961** [comment] 2015-11-19 03:23
@nicfit Also, don't make the mistake that I've been making in my lint cleanup commits of trying to incorporate too many disparate things in each commit. It's much easier on the reviewers, and thus more likely for a commit to be accepted, if it is small in scope and size. Fixing this issue is almost certainly going to require touching a lot of the code. I recommend doing it in bite-size self-contained pieces, even if that means a given block of code you just touched will be modified by a future commit in order to reach the final goal.

**Comment by scopatz** [comment] 2015-11-19 03:26
> Or were you implying that you would accept a PR to implement that var as a shortcut for the exit status of the most recent command?

Yes. I would accept a PR that implemented this, but only because it is what people expect - not because it is good.  

> It appears the correct way is builtins.__xonsh_history__.last_cmd_rtn but that is unwieldy.

Yeah. Perhaps an addition to the `history` command would be a better interface.

> @nicfit This is an important fix

I also think that this is important, but would appreciate a PR.

**Comment by krader1961** [comment] 2015-11-19 03:52
I'm confused, @scopatz. How can someone write a script in xonsh that executes external commands if they can't determine whether that command succeeded or failed? How would enhancing the `history` command improve the ability to write scripts? Referencing `builtins.__xonsh_history__.last_cmd_rtn` appears to be the only mechanism for a xonsh script to determine the exit status of the most recent (external) command. And that is currently broken. Is the expected syntax something like the following (which is obviously made up and broken):

```
#!/usr/bin/env xonsh
/usr/bin/false
if @(history -r) != 0:
    print('command failed')
```

You say

> I also think that this is important, but would appreciate a PR.

I asked @nicfit to open an issue so the xonsh community could discuss how best to proceed. For example, should the history record a single exit status that is the raw status returned by os.waitpid()? That is effectively what bash and zsh do with respect to `$?`. Or should xonsh preprocess the exit status to break it down into its constituent components and record whether the process generated a core dump, exited due to a signal, and if not what was its exit status? Or should it do a hybrid? That is, record both the raw and decomposed status values and make $? an alias for the raw exit status and also provide convenient ways to access the more nuanced aspects of the exit status?

**Comment by nicfit** [comment] 2015-11-19 03:58
Cool, I have consistency now...

TeePTYProc, Popen, SimpleProcProxy, and ProcProxy all have a 'returncode'.
TeePTYProc/Popen contain the process exit status, and no longer an os.wait
encoded value. The proxies are unchanged, it contains the function return
values. 

If the 'returncode' of a TeePTYProc/Popen is None then it will have a 'signal'
property containing a 2-tuple (signum, corebool).

Since TeePTYProc is Popen-like I made wait/poll return Popen-like retvals
rather then os.wait encoded values. They are not really used in xonsh but
should have matching semantics.

**Comment by scopatz** [comment] 2015-11-19 04:05
> Referencing builtins.__xonsh_history__.last_cmd_rtn appears to be the only mechanism for a xonsh script to determine the exit status of the most recent (external) command.

It is not, you can also access `__xonsh_history__.rtns[-1]`. Also, the line would be something like `if $(history -r) != '0':`, but yeah, you get the idea.

> And that is currently broken.

Also, the brokeness is only in some use cases.  Current master has the following behaviour:

```console
scopatz@artemis ~ $ $XONSH_STORE_STDOUT = False
scopatz@artemis ~ $ ls blob
/bin/ls: cannot access blob: No such file or directory
scopatz@artemis ~ $ __xonsh_history__.rtns[-1]
0
scopatz@artemis ~ $ $XONSH_STORE_STDOUT = True
scopatz@artemis ~ $ ls blob
/bin/ls: cannot access blob: No such file or directory
scopatz@artemis ~ $ __xonsh_history__.rtns[-1]
512
```

**Comment by nicfit** [comment] 2015-11-19 04:06
@krader1961 Yes, what I've implemented is the decomposed os.wait retval. The only info lost currently is history 'rtn' returncode, so we've lost the signal info. ... until add hist['signal'] exists.

**Comment by nicfit** [comment] 2015-11-19 04:08
@scopatz Using your example I get rtn=2

**Comment by scopatz** [comment] 2015-11-19 04:09
That is fine, probably different implementations of ls.  Non-zero error codes don't have a strict meaning other than "something bad happened"

**Comment by scopatz** [comment] 2015-11-19 04:10
Also @nicfit, does your branch affect the ability to background & foreground processes?

**Comment by krader1961** [comment] 2015-11-19 04:15
Not on my system:

```
$ xonsh
krader@macpro:~ > $XONSH_STORE_STDOUT
True
krader@macpro:~ > ls blob
/usr/local/opt/coreutils/libexec/gnubin/ls: cannot access blob: No such file or directory
krader@macpro:~ > __xonsh_history__.rtns[-1]
0
krader@macpro:~ > exit
$ ls blob
ls: cannot access blob: No such file or directory
$ echo $?
2
```

And I hope you're not suggesting that storing the data written to stdout be a prerequisite for capturing the exit status.

**Comment by scopatz** [comment] 2015-11-19 04:18
> And I hope you're not suggesting that storing the data written to stdout be a prerequisite for capturing the exit status.

I am not. I said it was a bug. But capturing the correct returncode is not completely broken, as shown here.

**Comment by krader1961** [comment] 2015-11-19 04:25
> But capturing the correct returncode is not completely broken, as shown here.

It's broken on my system which is running the latest version of the software. Also, a return code of 512 on a UNIX system means the process exited normally with a status of 2. The fact that @nicfit saw an exit status of 2 simply means he's reporting the status with his changes in place. It has nothing to do with different implementations of the ls command. The exit status is, by definition, limited to the range 0-255 on UNIX systems if you ignore the bits that indicate whether the status is due to a signal or core dump.

**Comment by krader1961** [comment] 2015-11-19 04:34
> capturing the correct returncode is not completely broken, as shown here.

It's broken on my system (Mac OS X 10.11) even with `$XONSH_STORE_STDOUT = True` in my ~/.xonshrc.

**Comment by scopatz** [comment] 2015-11-19 04:40
TeePTY only works on linux, so on other OSes it will fall back to the Popen behaviour.  I thought that there was some documentation about this somewhere, but I can't find it right this moment.

**Comment by nicfit** [comment] 2015-11-20 01:23
@scopatz Job control is not working, but no differently then I'm seeing on the master branch. Behavior is broken. I'm on Linux btw.

**Comment by nicfit** [comment] 2015-11-20 01:44
Hmm, I assume job control Ctrl-Z, bg, fg, etc. works for y'all? I'm seeing very odd behavior and it's different between  $XONSH_STORE_STDOUT as well.

**Comment by scopatz** [comment] 2015-11-20 02:01
I haven't tested the job control stuff recently. And I don't think it has ever been adequately tested when storing stdout.

**Comment by scopatz** [comment] 2015-11-20 02:01
I just wanted to make sure that this behaviour isn't different from master.

**Comment by nicfit** [comment] 2015-11-21 20:37
@scopatz  I messed around with stashing signal details in history, and then extended it to stashing exception details (for proxy commands, and builtins, etc) and then ran into the fact that the exception can't dump to json... I rolled that back (see the commits if interested).. Anyway, my branch as it stands fixes the original issue and then some, so I'll PR without. Extra error info in history dicts can come later if wished.

**Comment by scopatz** [comment] 2015-11-21 20:43
Cool, I look forward to your PR.

**Comment by scopatz** [comment] 2015-11-22 03:08
Please feel free to close this @nicfit

**Closed** 2015-11-22 10:12 UTC
Labels: bug
