### ISSUE TITLE
Jupyter kernel times out

### ISSUE THREAD

**Issue by esafak** [scopatz/xonsh#624] opened 2016-01-13 09:04 UTC
xonsh times out "waiting for kernel_info reply" and consequently does not work. I've tried deleting $HOME/.local/share/jupyter/kernels/xonsh and reinstalling xonsh (0.2.4). Here's some debug output from jupyter:

```
[D 00:59:45.560 NotebookApp] Found kernel xonsh in /home/user/.local/share/jupyter/kernels
[D 00:59:45.560 NotebookApp] Native kernel (python3) available from /home/user/.local/lib/python3.4/site-packages/ipykernel/resources
[D 00:59:45.561 NotebookApp] Starting kernel: ['/usr/bin/python3', '-m', 'xonsh.jupyter_kernel', '-f', '/run/user/1000/jupyter/kernel-51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5.json']
[D 00:59:45.602 NotebookApp] Connecting to: tcp://127.0.0.1:52111
[I 00:59:45.603 NotebookApp] Kernel started: 51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5
[D 00:59:45.603 NotebookApp] Kernel args: {'kernel_name': 'xonsh', 'cwd': 'user/directory'}
[D 00:59:45.603 NotebookApp] 201 POST /api/sessions (127.0.0.1) 47.00ms
[D 00:59:45.610 NotebookApp] Initializing websocket connection /api/kernels/51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5/channels
[D 00:59:45.613 NotebookApp] Requesting kernel info from 51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5
[D 00:59:45.613 NotebookApp] Connecting to: tcp://127.0.0.1:54302
[W 00:59:55.614 NotebookApp] Timeout waiting for kernel_info reply from 51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5
[D 00:59:55.615 NotebookApp] Opening websocket /api/kernels/51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5/channels
[D 00:59:55.619 NotebookApp] Connecting to: tcp://127.0.0.1:54302
[D 00:59:55.619 NotebookApp] Connecting to: tcp://127.0.0.1:34576
[D 00:59:55.620 NotebookApp] Connecting to: tcp://127.0.0.1:56287
```

The contents of the referenced `kernel-51a0038d-1f3d-43b8-8c1e-d6dfb14e2bf5.json` are:

```json
{
  "control_port": 52111,
  "transport": "tcp",
  "iopub_port": 34576,
  "signature_scheme": "hmac-sha256",
  "hb_port": 55385,
  "key": "fe6d34f9-2335-428f-a3f5-82d557cf332d",
  "stdin_port": 56287,
  "shell_port": 54302,
  "ip": "127.0.0.1"
}```

**Comment by scopatz** [comment] 2016-01-13 23:52
Thanks for opening this @esafak. This is definitely related to ipython/ipykernel#94 and Calysto/xonsh_kernel#2.  As @minrk points out, this is probably platform specific in some way.  Can you give us a few details about your machine? How did you get xonsh, what version of jupyter, etc.

**Comment by esafak** [comment] 2016-01-13 23:56
pip3, Ubuntu 14.04.3 LTS, jupyter 4.0.6. I also suspect something is wrong at jupyter's end.

**Comment by scopatz** [comment] 2016-01-13 23:58
OK that is the same as what I am running except that I am on the conda version.  So at least we can eliminate the package manager :)

**Comment by minrk** [comment] 2016-01-14 09:14
I should note that the Timeout seen in the logs is a *symptom*, not a cause of the failure to work. The problem is one level up, where the kernel is not finishing its startup, and thus not responding to messages, including the one that times out.

I'll try to set up an Ubuntu VM to see if I can set up an environment where this is reproducible and track it down. I haven't been able to do so on OS X.

**Comment by minrk** [comment] 2016-01-14 13:51
I've found the cause, but I don't really understand it. The KernelManager is calling `setpgrp` on the kernel, so that the kernel doesn't inherit signals from the parent. For some reason, the result is that invoking a subprocess that expects input (e.g. bash) hangs. Setting all inputs/outputs to pipes doesn't seem to help.

You can workaround this by setting sid in the subprocess call, but I'm not sure if that's the right solution.

If we switch the KernelManager to using setsid instead of setprgp we fix the hang, but bash subprocess calls start showing the error:

> cannot set terminal process group (-1): Inappropriate ioctl for device

In general, though, it seems like in the kernel case one shouldn't be calling `bash -i`, but `bash`, which eliminates the ioctl error messages, at least.

**Comment by minrk** [comment] 2016-01-14 14:00
The problem is caused by https://github.com/jupyter/jupyter_client/pull/68. If we switch to setsid, the hang will be fixed, but you will get Inappropriate ioctl messages from xonsh. I'm exploring that option at https://github.com/jupyter/jupyter_client/pull/109.

**Comment by takluyver** [comment] 2016-01-14 15:50
For the record, from further discussion in jupyter/jupyter_client#68: bash sends SIGTTIN to every other process in the same process group, including the kernel, which by default suspends them.

You should be able to avoid this by running bash in a new session:

```python
Popen(['bash', ...], start_new_session=True)
```

**Comment by scopatz** [comment] 2016-01-14 17:06
Thanks for tracking down the probable cause @minrk! And thanks @takluyver. That seems to be the correct solution to me.  I haven't tried it out yet though.

**Comment by scopatz** [comment] 2016-01-14 19:22
OK @esafak, the fix has been merged into master.  Would you mind trying this out?

**Comment by esafak** [comment] 2016-01-15 19:43
That was quick! It seems to work, but since I've never seen it actually work, I don't know what the proper behavior is. For example, is all output supposed to be sent to the shell rather than the browser? It feels unpleasant to type in one place and see the output elsewhere.

**Comment by scopatz** [comment] 2016-01-15 20:00
@esafak there is certainly another bug related to the output with our Jupyter kernel, but the problem of timing out is the question here.  Please open up another issue for that problem. Thanks!

**Closed** 2016-01-15 20:14 UTC
Labels: bug
