### ISSUE TITLE
Bash error on start

### ISSUE THREAD

**Issue by aig787** [scopatz/xonsh#208] opened 2015-04-15 23:46 UTC
On a base install of Fedora 20 Workstation I get 
```bash
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
```
when I try to launch xonsh. The link here https://kb.brightcomputing.com/faq/index.php?action=artikel&cat=2&id=239&artlang=en seems to suggest it has something to do with how bash handles functions post shellshock.

**Comment by aig787** [comment] 2015-04-16 00:22
The issue resolved itself. Couldn't tell you how or why, but it's very likely not anything xonsh was doing.

**Comment by scopatz** [comment] 2015-04-16 01:28
Weird, thanks for reporting, though.

**Comment by janpipek** [comment] 2015-06-18 07:50
I observe a similar behaviour when using `conda` command (or a few others):

```
> conda list
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
# packages in environment at /home/honza/anaconda/envs/py34:
#
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
alabaster                 0.7.3                    py34_0  
appdirs                   1.4.0                     <pip>
babel                     1.3                      py34_0
```

I wasn't able to find any scl use in either xonsh or conda sources, so it should come either from Python binary, bash or OS (and yes, it is also Fedora, v. 22)

**Comment by scopatz** [comment] 2015-06-19 11:48
Huh - weird @janpipek. `conda list` looks fine on my machine.  What version of conda are you on, what OS, etc.

**Comment by janpipek** [comment] 2015-06-20 08:03
* Fedora 22 - likely the culprit (as scl is Redhat stuff)
* conda 3.13.0 
* python 3.4.3
* GNU bash, version 4.3.39(1)-release (x86_64-redhat-linux-gnu)

I think we can leave conda out as e.g. running `alias` gives this:

```
$ alias
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
```

while (in normal bash):

```
$ which scl
scl ()
{ 
    local CMD=$1;
    if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
        eval "module $@";
    else
        /usr/bin/scl "$@";
    fi
}

$ which module
module ()
{ 
    eval `/usr/bin/modulecmd bash $*`
}
```
Seems it really has something to do with the link in the issue's first post and exported bash functions???

**Comment by scopatz** [comment] 2015-06-23 17:14
Ok! This almost certainly has to do with alias and/or exported functions and/or the tab completer. Out of curiosity what does `ls -l /bin/sh` print?

**Comment by janpipek** [comment] 2015-06-23 17:24
It's a symlink to /bin/bash.

**Comment by scopatz** [comment] 2015-06-23 17:33
Ahh OK.  I think I see the issue. Both of these functions are invalid Bash syntax.  Bash requires a semicolon at the end of the last statement in a function: http://tldp.org/LDP/abs/html/functions.html  This is only true when the function is defined on a single line - which maybe these are in their original source files.  Or maybe it is a bug in Bash.  Both of these functions, though, share a lack of a trailing semicolon.

**Comment by terrycloth** [comment] 2016-05-12 02:13
Can we reopen this issue? The bash errors persist for me on Fedora 23, with xonsh 0.2.7, installed using pip 8.1.2.

**Comment by scopatz** [comment] 2016-05-12 03:52
Sure @terrycloth. Do you have steps to reproduce? What are you seeing exactly?

**Comment by terrycloth** [comment] 2016-05-12 04:16
``` fish
> sudo pip install xonsh
> xonsh
```

Run through the configuration wizard, but leave everything at the default value except Mouse Support (which I enabled), AutoCD (which I enabled), and Case Sensitive Completions (which I disabled). Try restarting Xonsh.

``` fish
> xonsh
bash: module: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_module'
bash: scl: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_scl'
bash: module: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_module'
bash: scl: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_scl'
```

Which is *almost* the same as in the original post.

**Comment by scopatz** [comment] 2016-05-12 04:32
Looks like these are relevant:

* https://rc.fas.harvard.edu/shellshock-update-issue-temporarily-affecting-slurm-jobs-software-modules/
* https://kb.brightcomputing.com/faq/index.php?action=artikel&cat=2&id=239&artlang=en

**Comment by scopatz** [comment] 2016-05-12 04:36
@terrycloth what does your /etc/profile.d/modules.sh file look like?  Does it contain a `module()` function?

**Comment by scopatz** [comment] 2016-05-12 22:01
Also @terrycloth - can you try to `unset module` a la http://stackoverflow.com/a/11577652/2312428

**Comment by terrycloth** [comment] 2016-05-13 05:10
@scopatz The first two links you posted were about patches for the Shell Shock bug, in Bash 4.1. Are those still relevant to Bash 4.3.42? Should I add `source /etc/profile.d/modules.sh` to my `~/.bashrc` file?

**`/etc/profile.d/modules.sh` :**
``` bash
shell=`/bin/basename \`/bin/ps -p $$ -ocomm=\``
if [ -f /usr/share/Modules/init/$shell ]
then
  . /usr/share/Modules/init/$shell
else
  . /usr/share/Modules/init/sh
fi
```

And, sorry, but I don't understand what you mean by your comment about `unset module`. The StackOverflow answer you linked talks about commenting a line in `/usr/share/Modules/init/bash`. The [answer above it](https://stackoverflow.com/a/27130671) in the thread talks about adding `unset module` somewhere, but I that would mean editing one of the Xonsh bash scripts somewhere.

**Comment by scopatz** [comment] 2016-05-13 05:27
> Should I add source /etc/profile.d/modules.sh to my ~/.bashrc file

Yeah, I am interested to know if you try that, do the errors that you are seeing go away or change.

**Comment by scopatz** [comment] 2016-05-13 05:29
The `unset module` thing might be another option to try in the bashrc file.

**Comment by scopatz** [comment] 2016-05-13 05:30
Sorry it is hard for me to debug this issue since I am not seeing it myself.

**Comment by scopatz** [comment] 2016-05-13 05:34
This might be because I am on Ubuntu and don't see the modules stuff anywhere on my system.

**Comment by terrycloth** [comment] 2016-05-13 05:55
I tried all the combinations of `unset module` and/or `source /etc/profile.d/modules.sh` in `~/.bashrc`

Resourcing the modules does not seem to make a difference; adding `unset module` *reduces* the number of errors from 8 lines to 4, but there are still bash errors when starting xonsh, though.

``` fish
> xonsh
bash: scl: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_scl'
bash: scl: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_scl'
```

**Comment by scopatz** [comment] 2016-05-13 06:12
Ahh great!  What happens if you `unset module` and `unset scl`?  Also, for the record what OS are your running?

**Comment by terrycloth** [comment] 2016-05-14 02:48
I'm running Fedora 23, as I think I said when I reopened the thread.

`unset scl` seems to have fixed the last of the error messages. Seems funny that a bash configuration could cause troubles for a shell that ostensibly could replace Bash :P

Are we still calling this a bug in Xonsh, then, or is configuring Bash just a necessary step to add to the setup process?

Anyway, thanks!

**Comment by scopatz** [comment] 2016-05-14 06:19
Oh sorry, you did mention that you were on Fedora.  That left my short term memory :).

So I don't think that this is a xonsh bug per se, but rather something to do with how the OS has set up its default Bash configuration. 

That said, I agree that moving away from Bash would trigger this is funny / annoying.  @terrycloth, would you mind putting in a pull request with some docs that capture this issue and its solution? Maybe in the install docs page?

**Comment by scopatz** [comment] 2016-05-14 06:20
But really where ever you think it would fit.  Thanks!

**Comment by terrycloth** [comment] 2016-05-18 23:52
Sorry for the delayed response. Done.

**Comment by scopatz** [comment] 2016-05-19 00:56
Thanks @terrycloth! Please feel free to close this issue.

**Comment by terrycloth** [comment] 2016-05-19 01:07
I didn't open the issue, so I don't think I can.

**Comment by scopatz** [comment] 2016-05-19 01:09
Ahh ok. I'll close then.

**Closed by scopatz** 2016-05-19 01:09 UTC
Labels: bug
